{"pagelen": 100, "values": [{"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31/comments/2337676.json"}, "html": {"href": "#!/osrf/drcsim/issues/31#comment-2337676"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31.json"}}, "type": "issue", "id": 31, "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "title": "DRC simulator fails to launch"}, "content": {"raw": "looks like the client timed out waiting for server to come up.  Is this a intermittent error or is the failure consistent?", "markup": "markdown", "html": "<p>looks like the client timed out waiting for server to come up.  Is this a intermittent error or is the failure consistent?</p>", "type": "rendered"}, "created_on": "2012-11-08T04:05:33.647395+00:00", "user": {"display_name": "John Hsu", "uuid": "{0a186eae-abf0-4514-a951-23db5eccc286}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D"}, "html": {"href": "https://bitbucket.org/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:f3968cd3-4910-4384-8349-482a6c7889ec/5445ce6e-6273-47f0-84eb-621c86ca11cb/128"}}, "nickname": "hsu", "type": "user", "account_id": "557058:f3968cd3-4910-4384-8349-482a6c7889ec"}, "updated_on": null, "type": "issue_comment", "id": 2337676}, {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31/comments/2343227.json"}, "html": {"href": "#!/osrf/drcsim/issues/31#comment-2343227"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31.json"}}, "type": "issue", "id": 31, "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "title": "DRC simulator fails to launch"}, "content": {"raw": "I haven't tried to reproduce it, but Jenkins is [not having that problem](http://build.osrfoundation.org/job/drcsim-drcsim_1.0-devel-precise-amd64/1/testReport/?).  The `drcsim` tests include a [test](#!/osrf/drcsim/src/5a3eb819d344b8618810d969400c7a4554e0163b/ros/drc_robot_utils/test/drc_robot_publishers_hz.test?at=drcsim_1.0) that launches `drc_robot.launch` and verifies that data is being published via ROS.\n\nWhat happens if you try launching on a local machine?", "markup": "markdown", "html": "<p>I haven't tried to reproduce it, but Jenkins is <a data-is-external-link=\"true\" href=\"http://build.osrfoundation.org/job/drcsim-drcsim_1.0-devel-precise-amd64/1/testReport/\" rel=\"nofollow\">not having that problem</a>.  The <code>drcsim</code> tests include a <a data-is-external-link=\"true\" href=\"#!/osrf/drcsim/src/5a3eb819d344b8618810d969400c7a4554e0163b/ros/drc_robot_utils/test/drc_robot_publishers_hz.test?at=drcsim_1.0\" rel=\"nofollow\">test</a> that launches <code>drc_robot.launch</code> and verifies that data is being published via ROS.</p>\n<p>What happens if you try launching on a local machine?</p>", "type": "rendered"}, "created_on": "2012-11-08T17:44:34.937136+00:00", "user": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "updated_on": null, "type": "issue_comment", "id": 2343227}, {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31/comments/2343427.json"}, "html": {"href": "#!/osrf/drcsim/issues/31#comment-2343427"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31.json"}}, "type": "issue", "id": 31, "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "title": "DRC simulator fails to launch"}, "content": {"raw": "I reinstalled the drcsim and gazebo package on my local machine and it works if I use localhost as the ROS_IP (although the error is not the same) .... \n\nNext: checking for networking problems on a new cloud instance.", "markup": "markdown", "html": "<p>I reinstalled the drcsim and gazebo package on my local machine and it works if I use localhost as the ROS_IP (although the error is not the same) .... </p>\n<p>Next: checking for networking problems on a new cloud instance.</p>", "type": "rendered"}, "created_on": "2012-11-08T18:11:42.179667+00:00", "user": {"display_name": "Hugo Boyer", "uuid": "{3d87874e-7099-4981-b04f-57f0272faa7d}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D"}, "html": {"href": "https://bitbucket.org/%7B3d87874e-7099-4981-b04f-57f0272faa7d%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/21198da8539b599e3633017f5f5f8150d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsHB-6.png"}}, "nickname": "hugomatic", "type": "user", "account_id": "557058:869c02bb-b246-4cdc-9db3-0064e8add185"}, "updated_on": null, "type": "issue_comment", "id": 2343427}, {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31/comments/2346067.json"}, "html": {"href": "#!/osrf/drcsim/issues/31#comment-2346067"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31.json"}}, "type": "issue", "id": 31, "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "title": "DRC simulator fails to launch"}, "content": {"raw": "It wasn't reproducible, either on a local machine or a newly launched cloud machine.  It might have been due to a transient network/hostname problem.  In addition, we've stopped launching `gzclient` on the cloud machines, which should have the effect of reducing the chance of this happening again (assuming that the error was coming from `gzclient` failing to contact the master).", "markup": "markdown", "html": "<p>It wasn't reproducible, either on a local machine or a newly launched cloud machine.  It might have been due to a transient network/hostname problem.  In addition, we've stopped launching <code>gzclient</code> on the cloud machines, which should have the effect of reducing the chance of this happening again (assuming that the error was coming from <code>gzclient</code> failing to contact the master).</p>", "type": "rendered"}, "created_on": "2012-11-09T00:58:46.261795+00:00", "user": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "updated_on": null, "type": "issue_comment", "id": 2346067}, {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31/comments/2372743.json"}, "html": {"href": "#!/osrf/drcsim/issues/31#comment-2372743"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31.json"}}, "type": "issue", "id": 31, "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "title": "DRC simulator fails to launch"}, "content": {"raw": "Other users are reporting this same problem.  Details to be added.", "markup": "markdown", "html": "<p>Other users are reporting this same problem.  Details to be added.</p>", "type": "rendered"}, "created_on": "2012-11-13T01:09:53.551519+00:00", "user": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "updated_on": null, "type": "issue_comment", "id": 2372743}, {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31/comments/2372744.json"}, "html": {"href": "#!/osrf/drcsim/issues/31#comment-2372744"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31.json"}}, "type": "issue", "id": 31, "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "title": "DRC simulator fails to launch"}, "content": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "created_on": "2012-11-13T01:10:07.998708+00:00", "user": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "updated_on": null, "type": "issue_comment", "id": 2372744}, {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31/comments/2372768.json"}, "html": {"href": "#!/osrf/drcsim/issues/31#comment-2372768"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31.json"}}, "type": "issue", "id": 31, "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "title": "DRC simulator fails to launch"}, "content": {"raw": "(From [DRC Forum](http://forum.theroboticschallenge.org/index.php?topic=34.0))\n\nAfter the upgrade i am getting these Exceptions . Any thoughts on what could be the problem.?\nI  am using ubuntu 12.04 LTS\n\n    auto-starting new master\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[master]: started with pid [2666]\n    ROS_MASTER_URI=http://localhost:11311\n    \n    setting /run_id to 5fd87d2e-2aef-11e2-a1a8-00166f4cb957\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[rosout-1]: started with pid [2679]\n    started core service [/rosout]\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[gazebo-2]: started with pid [2682]\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[robot_state_publisher-3]: started with pid [2684]\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[pr2_mechanism_diagnostics-4]: started with pid [2685]\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[fake_joint_calibration-5]: started with pid [2686]\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[tf2_buffer_server-6]: started with pid [2687]\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[drc_robot_controllers_spawner-7]: started with pid [2690]\n    Exception AttributeError: AttributeError(\"'_DummyThread' object has no\n    attribute '_Thread__block'\",) in <module 'threading' from\n    '/usr/lib/python2.7/threading.pyc'> ignored\n    process[camhand_controllers_spawner-8]: started with pid [2691]\n    [ WARN] [1352521841.976941519]: You've passed in true for auto_start for\n    the C++ action server at [/tf2_buffer_server]. You should always pass in\n    false to avoid race conditions.\n    Gazebo multi-robot simulator, version 1.2\n    Copyright (C) 2011 Nate Koenig, John Hsu, and contributors.\n    Released under the Apache 2 License.\n    http://gazebosim.org\n    \n    Gazebo multi-robot simulator, version 1.2\n    Copyright (C) 2011 Nate Koenig, John Hsu, and contributors.\n    Released under the Apache 2 License.\n    http://gazebosim.org\n    \n    Error [Transport.cc:102] Unable to get topic namespaces in [50] tries.\n    Error [Node.cc:72] No namespace found\n    Warning [parser.cc:375] Gazebo SDF has no <gazebo> element in\n    file[/usr/share/drcsim-1.0/models/drc_robot/model.sdf]\n    Warning [parser_urdf.cc:1125] urdf2gazebo: link[left_camera_optical_frame]\n    has no inertia, parent joint [left_camera_optical_frame_joint] ignored\n    .Warning [parser_urdf.cc:1129] urdf2gazebo: link[left_camera_optical_frame]\n    has no inertia, not modeled in gazebo\n    Warning [parser_urdf.cc:1125] urdf2gazebo: link[right_camera_optical_frame]\n    has no inertia, parent joint [right_camera_optical_frame_joint] ignored\n    .Warning [parser_urdf.cc:1129] urdf2gazebo:\n    link[right_camera_optical_frame] has no inertia, not modeled in gazebo\n    X Error of failed request:  BadDrawable (invalid Pixmap or Window\n    parameter)\n      Major opcode of failed request:  136 (DRI2)\n      Minor opcode of failed request:  3 (DRI2CreateDrawable)\n      Resource id in failed request:  0x3e00002\n      Serial number of failed request:  28\n      Current serial number in output stream:  30\n    Warning [parser.cc:286] parse from urdf file\n    [/usr/share/drcsim-1.0/models/drc_robot/model.sdf].\n    [gazebo-2] process has finished cleanly\n    log file:\n    /home/gpeter/.ros/log/5fd87d2e-2aef-11e2-a1a8-00166f4cb957/gazebo-2*.log", "markup": "markdown", "html": "<p>(From <a data-is-external-link=\"true\" href=\"http://forum.theroboticschallenge.org/index.php?topic=34.0\" rel=\"nofollow\">DRC Forum</a>)</p>\n<p>After the upgrade i am getting these Exceptions . Any thoughts on what could be the problem.?\nI  am using ubuntu 12.04 LTS</p>\n<div class=\"codehilite\"><pre><span></span>auto-starting new master\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[master]: started with pid [2666]\nROS_MASTER_URI=http://localhost:11311\n\nsetting /run_id to 5fd87d2e-2aef-11e2-a1a8-00166f4cb957\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[rosout-1]: started with pid [2679]\nstarted core service [/rosout]\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[gazebo-2]: started with pid [2682]\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[robot_state_publisher-3]: started with pid [2684]\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[pr2_mechanism_diagnostics-4]: started with pid [2685]\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[fake_joint_calibration-5]: started with pid [2686]\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[tf2_buffer_server-6]: started with pid [2687]\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[drc_robot_controllers_spawner-7]: started with pid [2690]\nException AttributeError: AttributeError(&quot;&#39;_DummyThread&#39; object has no\nattribute &#39;_Thread__block&#39;&quot;,) in &lt;module &#39;threading&#39; from\n&#39;/usr/lib/python2.7/threading.pyc&#39;&gt; ignored\nprocess[camhand_controllers_spawner-8]: started with pid [2691]\n[ WARN] [1352521841.976941519]: You&#39;ve passed in true for auto_start for\nthe C++ action server at [/tf2_buffer_server]. You should always pass in\nfalse to avoid race conditions.\nGazebo multi-robot simulator, version 1.2\nCopyright (C) 2011 Nate Koenig, John Hsu, and contributors.\nReleased under the Apache 2 License.\nhttp://gazebosim.org\n\nGazebo multi-robot simulator, version 1.2\nCopyright (C) 2011 Nate Koenig, John Hsu, and contributors.\nReleased under the Apache 2 License.\nhttp://gazebosim.org\n\nError [Transport.cc:102] Unable to get topic namespaces in [50] tries.\nError [Node.cc:72] No namespace found\nWarning [parser.cc:375] Gazebo SDF has no &lt;gazebo&gt; element in\nfile[/usr/share/drcsim-1.0/models/drc_robot/model.sdf]\nWarning [parser_urdf.cc:1125] urdf2gazebo: link[left_camera_optical_frame]\nhas no inertia, parent joint [left_camera_optical_frame_joint] ignored\n.Warning [parser_urdf.cc:1129] urdf2gazebo: link[left_camera_optical_frame]\nhas no inertia, not modeled in gazebo\nWarning [parser_urdf.cc:1125] urdf2gazebo: link[right_camera_optical_frame]\nhas no inertia, parent joint [right_camera_optical_frame_joint] ignored\n.Warning [parser_urdf.cc:1129] urdf2gazebo:\nlink[right_camera_optical_frame] has no inertia, not modeled in gazebo\nX Error of failed request:  BadDrawable (invalid Pixmap or Window\nparameter)\n  Major opcode of failed request:  136 (DRI2)\n  Minor opcode of failed request:  3 (DRI2CreateDrawable)\n  Resource id in failed request:  0x3e00002\n  Serial number of failed request:  28\n  Current serial number in output stream:  30\nWarning [parser.cc:286] parse from urdf file\n[/usr/share/drcsim-1.0/models/drc_robot/model.sdf].\n[gazebo-2] process has finished cleanly\nlog file:\n/home/gpeter/.ros/log/5fd87d2e-2aef-11e2-a1a8-00166f4cb957/gazebo-2*.log\n</pre></div>", "type": "rendered"}, "created_on": "2012-11-13T01:13:39.967025+00:00", "user": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "updated_on": null, "type": "issue_comment", "id": 2372768}, {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31/comments/2372777.json"}, "html": {"href": "#!/osrf/drcsim/issues/31#comment-2372777"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31.json"}}, "type": "issue", "id": 31, "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "title": "DRC simulator fails to launch"}, "content": {"raw": "The `_DummyThread` error messages are a [known issue](https://code.ros.org/trac/ros/ticket/3950) in rospy caused by an [underlying problem](http://bugs.python.org/issue14308) in Python.  They can be ignored.", "markup": "markdown", "html": "<p>The <code>_DummyThread</code> error messages are a <a data-is-external-link=\"true\" href=\"https://code.ros.org/trac/ros/ticket/3950\" rel=\"nofollow\">known issue</a> in rospy caused by an <a data-is-external-link=\"true\" href=\"http://bugs.python.org/issue14308\" rel=\"nofollow\">underlying problem</a> in Python.  They can be ignored.</p>", "type": "rendered"}, "created_on": "2012-11-13T01:16:34.678020+00:00", "user": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "updated_on": null, "type": "issue_comment", "id": 2372777}, {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31/comments/2372797.json"}, "html": {"href": "#!/osrf/drcsim/issues/31#comment-2372797"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31.json"}}, "type": "issue", "id": 31, "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "title": "DRC simulator fails to launch"}, "content": {"raw": "The real problem here is evidenced by these two lines:\n\n    Error [Transport.cc:102] Unable to get topic namespaces in [50] tries.\n    Error [Node.cc:72] No namespace found\n\nA Gazebo node is failing to talk to the Gazebo master.  Anybody who's having this problem: is it 100% reproducible?  What happens if you launch without the GUI, which you do like so:\n\n    roslaunch drc_robot_utils drc_robot.launch gzname:=gzserver\n\nIf that starts up successfully, you can then start the GUI client separately:\n\n    gzclient", "markup": "markdown", "html": "<p>The real problem here is evidenced by these two lines:</p>\n<div class=\"codehilite\"><pre><span></span>Error [Transport.cc:102] Unable to get topic namespaces in [50] tries.\nError [Node.cc:72] No namespace found\n</pre></div>\n\n\n<p>A Gazebo node is failing to talk to the Gazebo master.  Anybody who's having this problem: is it 100% reproducible?  What happens if you launch without the GUI, which you do like so:</p>\n<div class=\"codehilite\"><pre><span></span>roslaunch drc_robot_utils drc_robot.launch gzname:=gzserver\n</pre></div>\n\n\n<p>If that starts up successfully, you can then start the GUI client separately:</p>\n<div class=\"codehilite\"><pre><span></span>gzclient\n</pre></div>", "type": "rendered"}, "created_on": "2012-11-13T01:20:53.236784+00:00", "user": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "updated_on": "2012-11-13T01:24:28.286165+00:00", "type": "issue_comment", "id": 2372797}, {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31/comments/2372851.json"}, "html": {"href": "#!/osrf/drcsim/issues/31#comment-2372851"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31.json"}}, "type": "issue", "id": 31, "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "title": "DRC simulator fails to launch"}, "content": {"raw": "Hmm, then there's this error:\n\n    X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)\n      Major opcode of failed request:  136 (DRI2)\n      Minor opcode of failed request:  3 (DRI2CreateDrawable)\n      Resource id in failed request:  0x3e00002\n      Serial number of failed request:  28\n      Current serial number in output stream:  30\n\nSo perhaps the server died because of an X rendering issue and as a result the GUI client couldn't talk to the master (which is in the server process).\n\nIs your GPU driver configuration working properly?  What does `glxinfo` say?", "markup": "markdown", "html": "<p>Hmm, then there's this error:</p>\n<div class=\"codehilite\"><pre><span></span>X Error of failed request:  BadDrawable (invalid Pixmap or Window parameter)\n  Major opcode of failed request:  136 (DRI2)\n  Minor opcode of failed request:  3 (DRI2CreateDrawable)\n  Resource id in failed request:  0x3e00002\n  Serial number of failed request:  28\n  Current serial number in output stream:  30\n</pre></div>\n\n\n<p>So perhaps the server died because of an X rendering issue and as a result the GUI client couldn't talk to the master (which is in the server process).</p>\n<p>Is your GPU driver configuration working properly?  What does <code>glxinfo</code> say?</p>", "type": "rendered"}, "created_on": "2012-11-13T01:32:25.628404+00:00", "user": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "updated_on": "2012-11-13T01:33:13.592953+00:00", "type": "issue_comment", "id": 2372851}, {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31/comments/2429241.json"}, "html": {"href": "#!/osrf/drcsim/issues/31#comment-2429241"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/drcsim/issues/31.json"}}, "type": "issue", "id": 31, "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "title": "DRC simulator fails to launch"}, "content": {"raw": "Assuming that the underlying problem is GPU configuration.  Re-open if there's something Gazebo-specific.", "markup": "markdown", "html": "<p>Assuming that the underlying problem is GPU configuration.  Re-open if there's something Gazebo-specific.</p>", "type": "rendered"}, "created_on": "2012-11-20T01:28:46.431808+00:00", "user": {"display_name": "Brian Gerkey", "uuid": "{3d8b5763-9dad-4be7-85c2-a7ab6cd49173}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D"}, "html": {"href": "https://bitbucket.org/%7B3d8b5763-9dad-4be7-85c2-a7ab6cd49173%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9/5fa9ec73-0fec-4860-a202-e34ae23b6a12/128"}}, "nickname": "Brian Gerkey", "type": "user", "account_id": "557058:2e35028e-9ad8-4d6a-a3a5-275159a304a9"}, "updated_on": null, "type": "issue_comment", "id": 2429241}], "page": 1, "size": 11}