{"priority": "blocker", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/drcsim.json"}, "html": {"href": "#!/osrf/drcsim"}, "avatar": {"href": "data/bytebucket.org/ravatar/{247b5408-ae91-4e3c-b2f9-a21994658d11}ts=c_plus_plus"}}, "type": "repository", "name": "drcsim", "full_name": "osrf/drcsim", "uuid": "{247b5408-ae91-4e3c-b2f9-a21994658d11}"}, "links": {"attachments": {"href": "data/repositories/osrf/drcsim/issues/323/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/drcsim/issues/323.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/drcsim/issues/323/watch"}, "comments": {"href": "data/repositories/osrf/drcsim/issues/323/comments_page=1.json"}, "html": {"href": "#!/osrf/drcsim/issues/323/gazebo-exiting-on-simulation-machine-in"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/drcsim/issues/323/vote"}}, "reporter": {"display_name": "sachih", "uuid": "{5b4b74fa-1172-4c6f-a38b-54ffaf7dbe2e}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B5b4b74fa-1172-4c6f-a38b-54ffaf7dbe2e%7D"}, "html": {"href": "https://bitbucket.org/%7B5b4b74fa-1172-4c6f-a38b-54ffaf7dbe2e%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/8bdeccc7f3489a8a046ba5c80a81892ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsS-5.png"}}, "nickname": "sachih", "type": "user", "account_id": "557058:cf468912-43ca-47b2-b8d6-3b90908dc837"}, "title": "Gazebo exiting on simulation machine in the cloud", "component": null, "votes": 0, "watches": 5, "content": {"raw": "I have had the simulator exit with the following error twice halfwaty through a driving task. \r\n\r\nError [parser.cc:99] Unable to load file[/usr/share/gazebo-1.8/sdf/1.4/joint.sdf]\r\nError [SDF.cc:761] Missing element description for [axis]\r\n[gazebo-2] process has finished cleanly\r\nlog file: /home/ubuntu/.ros/log/e3bd7f52-cfc4-11e2-9926-002590c0c2a8/gazebo-2*.log\r\n\r\nWe are using vrc_task_1.world. ", "markup": "markdown", "html": "<p>I have had the simulator exit with the following error twice halfwaty through a driving task. </p>\n<p>Error [parser.cc:99] Unable to load file[/usr/share/gazebo-1.8/sdf/1.4/joint.sdf]\nError [SDF.cc:761] Missing element description for [axis]\n[gazebo-2] process has finished cleanly\nlog file: /home/ubuntu/.ros/log/e3bd7f52-cfc4-11e2-9926-002590c0c2a8/gazebo-2*.log</p>\n<p>We are using vrc_task_1.world. </p>", "type": "rendered"}, "assignee": null, "state": "wontfix", "version": null, "edited_on": null, "created_on": "2013-06-07T23:37:47.491726+00:00", "milestone": null, "updated_on": "2013-06-11T03:09:47.695854+00:00", "type": "issue", "id": 323}